---
apiVersion: v1
kind: Deployment
metadata:
  name: windows-starter
  labels:
    app: timeapp
spec:
  containers:
    - name: backend
      image: docker.io/vaishnavihire/timeapp:updated_time
      ports:
        - containerPort: 8080