apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-starter
  labels:
    name: timeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timeapp
  template:
    metadata:
      labels:
        app: timeapp
    spec:
      containers:
        - image: docker.io/vaishnavihire/timeapp:updated_time
          name: timeapp
          ports:
            - containerPort: 8080